.DEFAULT_GOAL := all
.PHONY: all clean

# Flags passed to the C++ compiler.
CXXFLAGS += -ggdb3 -Wall -Wextra -pthread -std=c++17 -O3


all: au

clean:
	rm -f au

SRCS = src/CatCmd.cpp  src/Grep.cpp  src/Json2Au.cpp  src/Stats.cpp  src/Tail.cpp  src/Zindex.cpp  src/ZindexCmd.cpp  src/main.cpp

au: $(SRCS)
	$(CXX) $(CXXFLAGS) -Isrc -Iexternal/rapidjson/include -Iexternal/tclap/include -fuse-ld=gold -static $^ -lz -o $@
