#!/bin/bash

set -e

export FIG_REMOTE_URL=ftp://devnas/builds/Fig/repos
export LD_LIBRARY_PATH=${HOME}/.fighome/runtime/gcc/7.2.0-1/lib64
fig --no-file --log-level=warn \
    --suppress-cleanup-of-retrieves \
    --update-if-missing \
    --suppress-retrieves \
    clang/6.0.0-1-gcc7.2.0-1 \
    -- clang-tidy "$@"
