#!/bin/bash

set -e

export FIG_REMOTE_URL=ftp://devnas/builds/Fig/repos
fig --no-file --log-level=warn \
    --suppress-cleanup-of-retrieves \
    --update-if-missing \
    --suppress-retrieves \
    cmake/3.9.1 \
    -- cmake "$@"
